name: Build WPR Android ARMv7

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.408'

      - name: Verify SDK
        run: |
          dotnet --version
          dotnet --info

      - name: Show .NET info
        run: dotnet --info

      - name: Install Android workload
        run: dotnet workload install android

      - name: Restore
        run: dotnet restore Src/WPR.sln

      - name: Publish
        run: |
          dotnet publish \
          Src/UI/WPR.UI.Android/WPR.UI.Android.csproj \
          -c Release \
          -f net8.0-android34.0

      - name: Find APK
        run: find . -iname "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WPR-ARMv7
          path: |
            **/*.apk
